/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CardUpdate = IDL.Record({
  'setName' : IDL.Text,
  'types' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'setId' : IDL.Text,
  'imageUrl' : IDL.Text,
  'number' : IDL.Text,
  'quantity' : IDL.Nat,
  'marketPrice' : IDL.Float64,
  'rarity' : IDL.Text,
  'cardId' : IDL.Text,
  'customValue' : IDL.Opt(IDL.Float64),
  'condition' : IDL.Text,
});
export const PokemonCard = IDL.Record({
  'id' : IDL.Text,
  'setName' : IDL.Text,
  'types' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'setId' : IDL.Text,
  'imageUrl' : IDL.Text,
  'number' : IDL.Text,
  'quantity' : IDL.Nat,
  'marketPrice' : IDL.Float64,
  'rarity' : IDL.Text,
  'cardId' : IDL.Text,
  'customValue' : IDL.Opt(IDL.Float64),
  'dateAdded' : IDL.Int,
  'condition' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCard' : IDL.Func([CardUpdate], [PokemonCard], []),
  'analyzeCardImage' : IDL.Func([IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCollection' : IDL.Func([], [IDL.Vec(PokemonCard)], ['query']),
  'getVisionApiKey' : IDL.Func([], [IDL.Text], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeCard' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'setVisionApiKey' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCard' : IDL.Func([IDL.Text, CardUpdate], [PokemonCard], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CardUpdate = IDL.Record({
    'setName' : IDL.Text,
    'types' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'setId' : IDL.Text,
    'imageUrl' : IDL.Text,
    'number' : IDL.Text,
    'quantity' : IDL.Nat,
    'marketPrice' : IDL.Float64,
    'rarity' : IDL.Text,
    'cardId' : IDL.Text,
    'customValue' : IDL.Opt(IDL.Float64),
    'condition' : IDL.Text,
  });
  const PokemonCard = IDL.Record({
    'id' : IDL.Text,
    'setName' : IDL.Text,
    'types' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'setId' : IDL.Text,
    'imageUrl' : IDL.Text,
    'number' : IDL.Text,
    'quantity' : IDL.Nat,
    'marketPrice' : IDL.Float64,
    'rarity' : IDL.Text,
    'cardId' : IDL.Text,
    'customValue' : IDL.Opt(IDL.Float64),
    'dateAdded' : IDL.Int,
    'condition' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCard' : IDL.Func([CardUpdate], [PokemonCard], []),
    'analyzeCardImage' : IDL.Func([IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCollection' : IDL.Func([], [IDL.Vec(PokemonCard)], ['query']),
    'getVisionApiKey' : IDL.Func([], [IDL.Text], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeCard' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'setVisionApiKey' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCard' : IDL.Func([IDL.Text, CardUpdate], [PokemonCard], []),
  });
};

export const init = ({ IDL }) => { return []; };