/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CardUpdate {
  'setName' : string,
  'types' : Array<string>,
  'name' : string,
  'setId' : string,
  'imageUrl' : string,
  'number' : string,
  'quantity' : bigint,
  'marketPrice' : number,
  'rarity' : string,
  'cardId' : string,
  'customValue' : [] | [number],
  'condition' : string,
}
export interface PokemonCard {
  'id' : string,
  'setName' : string,
  'types' : Array<string>,
  'name' : string,
  'setId' : string,
  'imageUrl' : string,
  'number' : string,
  'quantity' : bigint,
  'marketPrice' : number,
  'rarity' : string,
  'cardId' : string,
  'customValue' : [] | [number],
  'dateAdded' : bigint,
  'condition' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCard' : ActorMethod<[CardUpdate], PokemonCard>,
  'analyzeCardImage' : ActorMethod<[string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllUsers' : ActorMethod<[], Array<Principal>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCollection' : ActorMethod<[], Array<PokemonCard>>,
  'getVisionApiKey' : ActorMethod<[], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeCard' : ActorMethod<[string], boolean>,
  'setVisionApiKey' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCard' : ActorMethod<[string, CardUpdate], PokemonCard>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];